import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {afterEach,describe,expect,it} from 'vitest';
import {drive,goodDrivePlan,resolveBuild,stockTune} from '@nitto/game-core';
import {GameService} from './service.js';
import {JsonStore} from './store.js';

const dirs:string[]=[];
async function setup(){const dir=await mkdtemp(join(tmpdir(),'nitto-api-'));dirs.push(dir);return new GameService(new JsonStore(join(dir,'db.json')));}
afterEach(async()=>{await Promise.all(dirs.splice(0).map(dir=>rm(dir,{recursive:true,force:true})));});
const timeline=(shiftRpm?:number)=>{const car=resolveBuild({carId:'civic-si',fittedPartIds:[]});return drive(car,stockTune(car),{...goodDrivePlan(91),...(shiftRpm===undefined?{}:{shiftRpm})}).timeline;};

describe('Stages 9–12 authoritative service',()=>{
  it('registers, hashes credentials and restores a profile with a session',async()=>{const service=await setup();const created=await service.register('Player One','correct horse');const me=await service.account(created.token);expect(me.profile.username).toBe('Player One');expect(me.garage.cash).toBe(10000);const raw=await readFile(dirs[0]+'/db.json','utf8');expect(raw).not.toContain('correct horse');expect((await service.login('player one','correct horse')).profile.username).toBe('Player One');});
  it('searches public profiles without exposing credentials or garages',async()=>{const service=await setup();const a=await service.register('Alpha Racer','password1'),b=await service.register('Beta Racer','password2');const found=await service.search(a.token,'beta');expect(found).toEqual([expect.objectContaining({id:b.profile.id,username:'Beta Racer'})]);expect(found[0]).not.toHaveProperty('garage');});
  it('hides and locks the challenger run until the defender settles escrow once',async()=>{const service=await setup();const left=await service.register('Left Lane','password1'),right=await service.register('Right Lane','password2');const opened=await service.createChallenge(left.token,{defenderId:right.profile.id,mode:'heads-up',wager:500,timeline:timeline()});const before=JSON.stringify((await service.listChallenges(left.token))[0]);await service.garageAction(left.token,{type:'tune',tune:{gearRatios:[3.1,1.9,1.3,1,0.8],finalDrive:4.2}});expect(JSON.stringify((await service.listChallenges(left.token))[0])).toBe(before);const incoming=(await service.listChallenges(right.token))[0]!;expect(incoming.challengerRun.slip).toBeNull();const done=await service.answerChallenge(right.token,opened.id,{timeline:timeline()});expect(done.status).toBe('completed');expect(done.challengerRun.slip).not.toBeNull();await expect(service.answerChallenge(right.token,opened.id,{timeline:timeline()})).rejects.toMatchObject({status:404});const balances=[(await service.account(left.token)).garage.cash,(await service.account(right.token)).garage.cash];expect(balances.reduce((a,b)=>a+b,0)).toBe(20000);});
  it('creates a team, accepts an applicant and protects withdrawals',async()=>{const service=await setup();const leader=await service.register('Team Lead','password1'),member=await service.register('Team Mate','password2');let team=await service.createTeam(leader.token,'Night Shift');await service.applyToTeam(member.token,team.id);team=await service.decideApplicant(leader.token,team.id,member.profile.id,true);expect(team.memberIds).toContain(member.profile.id);team=await service.teamBank(member.token,team.id,300);expect(team.bank).toBe(300);await expect(service.teamBank(member.token,team.id,-100)).rejects.toMatchObject({status:403});expect((await service.teamBank(leader.token,team.id,-100)).bank).toBe(200);});
  it('escrows team challenges and updates team records exactly once',async()=>{const service=await setup();const left=await service.register('Left Leader','password1'),right=await service.register('Right Leader','password2');const leftTeam=await service.createTeam(left.token,'Left Team'),rightTeam=await service.createTeam(right.token,'Right Team');await service.teamBank(left.token,leftTeam.id,1000);await service.teamBank(right.token,rightTeam.id,1000);const opened=await service.createTeamChallenge(left.token,{defenderTeamId:rightTeam.id,mode:'heads-up',wager:400,timeline:timeline()});expect((await service.listTeamChallenges(right.token))[0]!.challengerRun.slip).toBeNull();await service.answerTeamChallenge(right.token,opened.id,{timeline:timeline(4500)});await expect(service.answerTeamChallenge(right.token,opened.id,{timeline:timeline()})).rejects.toMatchObject({status:404});const teams=await service.listTeams(left.token);expect(teams.reduce((sum,team)=>sum+team.bank,0)).toBe(2000);expect(teams.reduce((sum,team)=>sum+team.wins,0)).toBe(1);expect(teams.reduce((sum,team)=>sum+team.losses,0)).toBe(1);});
});
