import {copyFile,mkdir,readFile,rename,writeFile} from 'node:fs/promises';import {dirname} from 'node:path';import {migrateAppearance,type GarageState,type OwnedCarState} from '@nitto/game-core';import type {Database} from './types.js';
const EMPTY:Database={schemaVersion:2,accounts:[],sessions:[],challenges:[],teams:[]};
export class JsonStore{private queue=Promise.resolve();constructor(readonly path:string){}async read():Promise<Database>{try{const parsed=JSON.parse(await readFile(this.path,'utf8')) as Partial<Database>;return migrate(parsed);}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return structuredClone(EMPTY);throw error;}}async update<T>(mutation:(database:Database)=>T|Promise<T>):Promise<T>{let result!:T;this.queue=this.queue.catch(()=>undefined).then(async()=>{const database=await this.read();result=await mutation(database);await mkdir(dirname(this.path),{recursive:true});const temp=`${this.path}.tmp`;await writeFile(temp,JSON.stringify(database,null,2),'utf8');await rename(temp,this.path);});await this.queue;return result;}async backup():Promise<string>{await mkdir(`${dirname(this.path)}/backups`,{recursive:true});const target=`${dirname(this.path)}/backups/nitto-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;await copyFile(this.path,target);return target;}}
export function migrate(value:Partial<Database>):Database{
  const accounts=Array.isArray(value.accounts)?value.accounts.map(account=>({...account,garage:migrateGarage(account.id,account.garage)})):[];
  const challenges=Array.isArray(value.challenges)?value.challenges.map(challenge=>{const challengerGarage=migrateGarage(`challenge-${challenge.id}-left`,challenge.challengerRun.garageSnapshot),challengerRun={...challenge.challengerRun,garageSnapshot:challengerGarage,vehicleId:challenge.challengerRun.vehicleId??challengerGarage.selectedVehicleId??`legacy-${challenge.id}-left`};if(!challenge.defenderRun)return{...challenge,challengerRun};const defenderGarage=migrateGarage(`challenge-${challenge.id}-right`,challenge.defenderRun.garageSnapshot),defenderRun={...challenge.defenderRun,garageSnapshot:defenderGarage,vehicleId:challenge.defenderRun.vehicleId??defenderGarage.selectedVehicleId??`legacy-${challenge.id}-right`};return{...challenge,challengerRun,defenderRun};}):[];
  return{schemaVersion:2,accounts,sessions:Array.isArray(value.sessions)?value.sessions:[],challenges,teams:Array.isArray(value.teams)?value.teams:[]};
}

function migrateGarage(scope:string,garage:GarageState):GarageState{
  const old=garage as GarageState&{selectedVehicleId?:string;nextVehicleSequence?:number},hasSelectedCar=old.hasSelectedCar??true,selectedVehicleId=hasSelectedCar?(old.selectedVehicleId??`legacy-${scope}-selected`):null,seen=new Set<string>(selectedVehicleId?[selectedVehicleId]:[]);
  const ownedCars=(old.ownedCars??[]).map((vehicle,index)=>{let vehicleId=(vehicle as Partial<OwnedCarState>).vehicleId??`legacy-${scope}-${index+2}`;while(seen.has(vehicleId))vehicleId=`${vehicleId}-copy`;seen.add(vehicleId);return{...vehicle,vehicleId,appearance:migrateAppearance(vehicle.appearance)};});
  return{...old,hasSelectedCar,selectedVehicleId,nextVehicleSequence:Math.max(old.nextVehicleSequence??1,ownedCars.length+(hasSelectedCar?2:1)),appearance:migrateAppearance(old.appearance),ownedCars};
}
