import type { Appearance,CpuDifficulty,GarageState,InputTimeline,RaceMode,TimingSlip,Tune } from '@nitto/game-core';
const BASE=import.meta.env.VITE_API_URL??(import.meta.env.DEV?'http://127.0.0.1:8787':'');
export interface OnlineProfile{id:string;username:string;record:GarageState['record'];selectedCarId:string|null;}
export interface AuthResult{token:string;profile:OnlineProfile;garage:GarageState;raceHistory?:TimingSlip[];}
export const onlineAvailable=BASE.length>0;
async function request<T>(path:string,options:RequestInit={},token=''):Promise<T>{if(!BASE)throw new Error('Online server is not configured for this deployment.');const response=await fetch(`${BASE}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const data=await response.json() as T&{error?:string};if(!response.ok)throw new Error(data.error??`Request failed (${response.status})`);return data;}
export const api={register:(username:string,password:string)=>request<AuthResult>('/api/register',{method:'POST',body:JSON.stringify({username,password})}),login:(username:string,password:string)=>request<AuthResult>('/api/login',{method:'POST',body:JSON.stringify({username,password})}),me:(token:string)=>request<{profile:OnlineProfile;garage:GarageState}>('/api/me',{},token),players:(token:string,q:string)=>request<OnlineProfile[]>(`/api/players?q=${encodeURIComponent(q)}`,{},token),publicGarage:(token:string,accountId:string)=>request<{profile:OnlineProfile;selectedVehicleId:string|null;vehicles:Array<{vehicleId:string;modelId:string;appearance:Appearance;fittedPartCount:number;condition:number}>}>(`/api/players/${encodeURIComponent(accountId)}/garage`,{},token),garage:(token:string,action:{type:string;id?:string;tune?:Tune;appearance?:Appearance})=>request<GarageState>('/api/garage/action',{method:'POST',body:JSON.stringify(action)},token),cpuRace:(token:string,difficulty:CpuDifficulty,timeline:InputTimeline)=>request<{won:boolean;garage:GarageState}>('/api/cpu-races',{method:'POST',body:JSON.stringify({difficulty,timeline})},token),challenges:(token:string)=>request<unknown[]>('/api/challenges',{},token),createChallenge:(token:string,input:{defenderId:string;mode:RaceMode;wager:number;dialIn?:number;timeline:InputTimeline})=>request<unknown>('/api/challenges',{method:'POST',body:JSON.stringify(input)},token),answerChallenge:(token:string,id:string,timeline:InputTimeline,dialIn?:number)=>request<unknown>(`/api/challenges/${id}/answer`,{method:'POST',body:JSON.stringify({timeline,...(dialIn===undefined?{}:{dialIn})})},token),createTeam:(token:string,name:string)=>request<unknown>('/api/teams',{method:'POST',body:JSON.stringify({name})},token),applyTeam:(token:string,id:string)=>request<unknown>(`/api/teams/${id}/apply`,{method:'POST',body:'{}'},token),teamBank:(token:string,id:string,amount:number)=>request<unknown>(`/api/teams/${id}/bank`,{method:'POST',body:JSON.stringify({amount})},token)};
export const teamsApi={list:(token:string)=>request<unknown[]>('/api/teams',{},token),invite:(token:string,teamId:string,accountId:string)=>request<unknown>(`/api/teams/${teamId}/invites/${accountId}`,{method:'POST',body:'{}'},token),accept:(token:string,teamId:string)=>request<unknown>(`/api/teams/${teamId}/accept`,{method:'POST',body:'{}'},token)};
export const teamChallengeApi={list:(token:string)=>request<unknown[]>('/api/team-challenges',{},token),create:(token:string,input:{defenderTeamId:string;mode:RaceMode;wager:number;dialIn?:number;timeline:InputTimeline})=>request<unknown>('/api/team-challenges',{method:'POST',body:JSON.stringify(input)},token),answer:(token:string,id:string,timeline:InputTimeline,dialIn?:number)=>request<unknown>(`/api/team-challenges/${id}/answer`,{method:'POST',body:JSON.stringify({timeline,...(dialIn===undefined?{}:{dialIn})})},token)};
