import {useEffect,useState} from 'react';
import type {InputTimeline,RaceMode,TimingSlip} from '@nitto/game-core';
import {api,type OnlineProfile} from '../onlineApi.js';

interface ChallengeView{id:string;challengerId:string;defenderId:string;mode:RaceMode;wager:number;status:'incoming'|'completed';winnerId?:string;challengerRun:{slip:TimingSlip|null};defenderRun?:{slip:TimingSlip|null};}

export function ChallengeScreen({token,profile,lastRun}:{token:string;profile:OnlineProfile|null;lastRun:{slip:TimingSlip;timeline:InputTimeline}|null}){
  const [items,setItems]=useState<ChallengeView[]>([]),[query,setQuery]=useState(''),[players,setPlayers]=useState<OnlineProfile[]>([]),[selected,setSelected]=useState<OnlineProfile|null>(null),[mode,setMode]=useState<RaceMode>('heads-up'),[wager,setWager]=useState(0),[dial,setDial]=useState(15),[message,setMessage]=useState('');
  const load=()=>{if(token)void api.challenges(token).then(value=>setItems(value as ChallengeView[])).catch(error=>setMessage(String(error)));};
  useEffect(load,[token]);
  if(!token||!profile)return <div className="screen online-gate"><h2>Challenge Info</h2><p>Sign in from Main to send and receive asynchronous races.</p></div>;
  const search=()=>void api.players(token,query).then(value=>setPlayers(value.filter(player=>player.id!==profile.id))).catch(error=>setMessage(String(error)));
  const create=()=>{if(!selected||!lastRun)return;void api.createChallenge(token,{defenderId:selected.id,mode,wager,timeline:lastRun.timeline,...(mode==='bracket'?{dialIn:dial}:{})}).then(()=>{setMessage('Challenge sent. Your result is locked and hidden.');load();}).catch(error=>setMessage(error instanceof Error?error.message:'Failed.'));};
  const answer=(item:ChallengeView)=>{if(!lastRun)return;void api.answerChallenge(token,item.id,lastRun.timeline,item.mode==='bracket'?dial:undefined).then(()=>{setMessage('Run submitted. Result settled.');load();}).catch(error=>setMessage(error instanceof Error?error.message:'Failed.'));};
  return <div className="screen challenge-center"><header><span>Member Competition</span><h2>Challenge Info</h2><b>{items.filter(item=>item.status==='incoming'&&item.defenderId===profile.id).length} incoming</b></header><div className="challenge-create"><section><h3>Find a racer</h3><div><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Player name"/><button onClick={search}>Search</button></div><ul>{players.map(player=><li key={player.id}><button className={selected?.id===player.id?'active':''} onClick={()=>setSelected(player)}><strong>{player.username}</strong><span>{player.record.wins}–{player.record.losses}</span></button></li>)}</ul></section><section><h3>Race terms</h3><label>Race type<select value={mode} onChange={event=>setMode(event.target.value as RaceMode)}><option value="heads-up">Heads-up</option><option value="bracket">Bracket</option></select></label>{mode==='bracket'&&<label>Dial-in<input type="number" step=".01" min="5" max="30" value={dial} onChange={event=>setDial(Number(event.target.value))}/></label>}<label>Cash wager<input type="number" min="0" max="1000000" value={wager} onChange={event=>setWager(Number(event.target.value))}/></label><button disabled={!selected||!lastRun} onClick={create}>Lock Latest Pass &amp; Send</button><small>{lastRun?`Latest pass: ${lastRun.slip.quarterMileEt.toFixed(3)} sec`:'Complete a Race Track pass first.'}</small></section></div><section className="challenge-list"><h3>Incoming, outgoing &amp; completed</h3>{items.length?items.map(item=>{const incoming=item.status==='incoming'&&item.defenderId===profile.id;return <article key={item.id}><div><span>{item.mode} · ${item.wager.toLocaleString()}</span><strong>{incoming?'Incoming challenge':item.status==='incoming'?'Awaiting opponent':item.winnerId===profile.id?'Victory':'Completed'}</strong></div>{incoming?<button disabled={!lastRun} onClick={()=>answer(item)}>Race With Latest Pass</button>:<small>{item.status==='incoming'?'Your ET remains hidden':item.challengerRun.slip?`${item.challengerRun.slip.quarterMileEt.toFixed(3)} sec`:'Settled'}</small>}</article>}):<p>No online challenges yet.</p>}</section><p className="challenge-message">{message}</p></div>;
}
