import {useState} from 'react';
import {getCar,type Appearance} from '@nitto/game-core';
import {api,type OnlineProfile} from '../onlineApi.js';
import {VehiclePortrait} from './WorkshopFrame.js';

interface PublicGarage {profile:OnlineProfile;selectedVehicleId:string|null;vehicles:Array<{vehicleId:string;modelId:string;appearance:Appearance;fittedPartCount:number;condition:number}>}

export function CommunityScreen({token,profile}:{token:string;profile:OnlineProfile|null}){
  const [query,setQuery]=useState(''),[players,setPlayers]=useState<OnlineProfile[]>([]),[message,setMessage]=useState('Search the member directory by racer name.'),[showcase,setShowcase]=useState<PublicGarage|null>(null);
  if(!token||!profile)return <div className="screen community-center"><header><span>1320 Network</span><h2>Community</h2><b>Guest</b></header><section className="community-gate"><h3>Member directory offline</h3><p>Sign in from Main to find racers, inspect records and send a challenge from Challenge Info.</p></section></div>;
  const search=()=>void api.players(token,query).then(results=>{setPlayers(results);setMessage(results.length?`${results.length} racer${results.length===1?'':'s'} found.`:'No matching racers.');}).catch(error=>setMessage(error instanceof Error?error.message:'Search failed.'));
  const viewGarage=(player:OnlineProfile)=>void api.publicGarage(token,player.id).then(value=>setShowcase(value)).catch(error=>setMessage(error instanceof Error?error.message:'Garage unavailable.'));
  return <div className="screen community-center"><header><span>1320 Network</span><h2>Community</h2><b>{profile.username}</b></header><section className="community-search"><h3>Member Search</h3><div><input value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>event.key==='Enter'&&search()} placeholder="Racer name"/><button onClick={search}>Search</button></div></section>{showcase?<section className="public-garage"><header><div><span>Public Vehicle Showcase</span><h3>{showcase.profile.username}'s Garage</h3></div><button type="button" onClick={()=>setShowcase(null)}>Back to Members</button></header><div>{showcase.vehicles.map(vehicle=>{const car=getCar(vehicle.modelId);return <article key={vehicle.vehicleId} className={vehicle.vehicleId===showcase.selectedVehicleId?'selected':''}><VehiclePortrait carId={vehicle.modelId} appearance={vehicle.appearance}/><strong>{car.manufacturer} {car.displayName}</strong><small>{vehicle.fittedPartCount} upgrades · {vehicle.condition.toFixed(0)}% condition</small><em>{vehicle.vehicleId===showcase.selectedVehicleId?'Currently racing':'Garaged'}</em></article>;})}</div>{!showcase.vehicles.length&&<p>This member has not purchased a vehicle yet.</p>}</section>:<section className="community-results">{players.map(player=><article key={player.id}><i/><div><span>Member</span><strong>{player.username}</strong><small>Selected car: {player.selectedCarId??'None'}</small></div><b>{player.record.wins}–{player.record.losses}</b><button type="button" onClick={()=>viewGarage(player)}>View Garage</button></article>)}</section>}<p className="challenge-message">{message}</p></div>;
}
