import { CPU_OPPONENTS,CPU_PRIZES,type CpuDifficulty,type GarageState } from '@nitto/game-core';
import type { ReactNode } from 'react';

export function MainScreen({state,onRace,onVisitShowroom,playerName,accountPanel}:{state:GarageState;onRace:(difficulty:CpuDifficulty)=>void;onVisitShowroom:()=>void;playerName?:string;accountPanel?:ReactNode}){
  const winRate=state.record.races?Math.round(state.record.wins/state.record.races*100):0;
  return <div className="screen main-hub"><section className="main-profile"><header><span>Member Overview</span><h2>{playerName?`${playerName}'s Garage`:'Your Garage'}</h2><strong>${state.cash.toLocaleString()}</strong></header><div className="main-profile__stats"><div><span>Record</span><b>{state.record.wins}–{state.record.losses}</b></div><div><span>Win rate</span><b>{winRate}%</b></div><div><span>Condition</span><b>{state.hasSelectedCar?`${state.condition.toFixed(0)}%`:'—'}</b></div><div><span>Cars owned</span><b>{state.hasSelectedCar?state.ownedCars.length+1:0}</b></div></div>{!state.hasSelectedCar&&<div className="main-empty-garage"><p>Your garage is empty. Choose your first car, then its paint, parts and tune will follow it everywhere.</p><button type="button" onClick={onVisitShowroom}>Choose Your First Car</button></div>}</section>
    <section className="cpu-lobby"><header><span>Test &amp; Tune Night</span><h2>CPU Race Lobby</h2><p>{state.hasSelectedCar?'Pick an opponent. First to the stripe wins; reaction time counts.':'Purchase and select a car before entering a race.'}</p></header><div className="cpu-grid">{(['easy','medium','hard'] as const).map((difficulty,index)=>{const opponent=CPU_OPPONENTS[difficulty];return <article key={difficulty} className={`cpu-card cpu-card--${difficulty}`}><div className="cpu-card__portrait"><i/><strong>{index+1}</strong></div><span>{opponent.subtitle}</span><h3>{opponent.name}</h3><dl><div><dt>Difficulty</dt><dd>{difficulty}</dd></div><div><dt>Prize</dt><dd>${CPU_PRIZES[difficulty].toLocaleString()}</dd></div></dl><button type="button" disabled={!state.hasSelectedCar} onClick={()=>onRace(difficulty)}>Challenge</button></article>;})}</div></section>
    <section className="transaction-log"><header><h3>Account Activity</h3><span>Last {Math.min(6,state.transactions.length)} transactions</span></header>{state.transactions.length?<ul>{[...state.transactions].slice(-6).reverse().map(item=><li key={item.id}><span>{item.description}</span><b className={item.amount>=0?'credit':'debit'}>{item.amount>=0?'+':''}${item.amount.toLocaleString()}</b></li>)}</ul>:<p>No transactions yet. Win a race or visit the Speedshop.</p>}</section>
    {accountPanel}
  </div>;
}
