import {useMemo,useState} from 'react';
import {CARS,carUnlockReason,kwToHp,ownedCarIds,powerKwAtRpm,type GarageState} from '@nitto/game-core';

export function ShowroomScreen({state,message,onBuy,onSelect}:{state:GarageState;message:string;onBuy:(id:string)=>void;onSelect:(id:string)=>void}){
  const cars=[...CARS.values()],[selectedId,setSelectedId]=useState(state.build.carId),car=cars.find(item=>item.id===selectedId)??cars[0]!,owned=new Set(ownedCarIds(state)),locked=carUnlockReason(state,car.id);
  const peakHp=useMemo(()=>Math.max(...car.engine.curve.map(point=>kwToHp(powerKwAtRpm(car.engine.curve,point.rpm)))),[car]);
  const art=car.special?`assets/special-${car.id}.webp`:'assets/garage-civic-ek.webp';
  return <div className="screen showroom"><header><span>{car.special?'1320 Pro Division':'1320 Motors'}</span><h2>Car Showroom</h2><strong>${state.cash.toLocaleString()}</strong></header><div className="showroom-stage"><div className={`showroom-car showroom-car--${car.id} ${car.special?'showroom-car--special':''}`}><div className="showroom-spotlight"/><img src={`${import.meta.env.BASE_URL}${art}`} alt="" draggable={false}/>{car.special&&<b className="showroom-special-badge">Career Special</b>}<span>{car.manufacturer}</span><h3>{car.displayName}</h3></div><section className="showroom-spec"><span>{car.year} model</span><h2>{car.manufacturer} {car.displayName}</h2><dl><Spec label="Power" value={`${Math.round(peakHp)} hp`}/><Spec label="Weight" value={`${car.chassis.massKg} kg`}/><Spec label="Drive" value={car.drivetrain}/><Spec label="Gearbox" value={`${car.gearbox.gearRatios.length}-speed`}/></dl><div className="showroom-price"><span>Vehicle price</span><strong>${car.price.toLocaleString()}</strong></div>{car.id===state.build.carId?<button disabled>Currently Selected</button>:owned.has(car.id)?<button onClick={()=>onSelect(car.id)}>Select From Garage</button>:<button disabled={Boolean(locked)||state.cash<car.price} onClick={()=>onBuy(car.id)}>{locked?'Career Locked':'Purchase Vehicle'}</button>}<p>{message||locked||`${owned.size} of ${cars.length} vehicles owned`}</p></section></div><nav className="showroom-roster" aria-label="Vehicle roster">{cars.map(item=>{const reason=carUnlockReason(state,item.id);return <button key={item.id} className={`${item.id===car.id?'active':''} ${item.special?'special':''}`} aria-pressed={item.id===car.id} onClick={()=>setSelectedId(item.id)}><i className={`mini-car mini-car--${item.id}`}/><span>{item.special?'Pro Division':item.manufacturer}</span><strong>{item.displayName}</strong><small>{owned.has(item.id)?item.id===state.build.carId?'Selected':'Owned':reason??`$${item.price.toLocaleString()}`}</small></button>;})}</nav></div>;
}
function Spec({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>;}
