import {describe,expect,it} from 'vitest';
import {factoryPaintAppearance,migrateAppearance,stockAppearance,validateAppearance} from './customization.js';

describe('vehicle customization recipes',()=>{
  it('migrates old recipes to factory specification while preserving colour',()=>{const appearance=migrateAppearance({hue:300,saturation:60,brightness:90,graphicsHue:20,wheelStyle:2,rideHeight:-15});expect(appearance).toEqual(factoryPaintAppearance({hue:300}));});
  it('strips dormant visual categories from the production appearance',()=>{const rich={...stockAppearance(),hue:310,finishId:'matte' as const,graphicsId:'twin-stripe' as const,wheelStyle:2,rideHeight:-20,components:{...stockAppearance().components,wheels:'wheel-mesh',spoiler:'spoiler-gt'},decals:[{instanceId:'door-star',decalId:'decal-star',surface:'left-door' as const,x:.5,y:.5,scale:.4,rotation:0,colorHue:55}]};expect(factoryPaintAppearance(rich)).toEqual(factoryPaintAppearance({hue:310}));});
  it('accepts catalogue components and positioned decals',()=>{const appearance={...stockAppearance(),finishId:'matte' as const,graphicsId:'twin-stripe' as const,components:{...stockAppearance().components,spoiler:'spoiler-gt',roof:'roof-sunroof'},decals:[{instanceId:'door-star',decalId:'decal-star',surface:'left-door' as const,x:.45,y:.6,scale:.4,rotation:-8,colorHue:55}]};expect(validateAppearance(appearance,'civic-si')).toMatchObject({ok:true,appearance:{finishId:'matte',graphicsId:'twin-stripe',components:{spoiler:'spoiler-gt',roof:'roof-sunroof'},decals:[{instanceId:'door-star'}]}});});
  it('rejects unknown components, duplicate decal identities and unbounded placement',()=>{const stock=stockAppearance();expect(validateAppearance({...stock,components:{...stock.components,spoiler:'spoiler-hacked'}},'civic-si')).toMatchObject({ok:false});const decal={instanceId:'same',decalId:'decal-star',surface:'hood' as const,x:2,y:.5,scale:.4,rotation:0,colorHue:20};expect(validateAppearance({...stock,decals:[decal]},'civic-si')).toMatchObject({ok:false});});
});
